apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: xvag/instavote-vote:v13
        name: vote
