apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/deployment.yaml
- ../base/service.yaml
patchesStrategicMerge:
- deployment.yaml

namespace: instavote

replicas:
- name: vote
  count: 2

images:
- name: xvag/instavote-vote
#  newName: xvag/vote
  newTag: latest
