---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redis-staging
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: redis
    namespace: instavote
  interval: 1m0s
  path: ./kustomize/redis/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  targetNamespace: instavote
  timeout: 2m0s
