---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: result-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm/charts/result/staging
      sourceRef:
        kind: GitRepository
        name: instavote-deploy
  interval: 1m0s
  targetNamespace: instavote
