---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: github-instavote
  timeout: 1m0s
  url: https://github.com/xvag/instavote-deploy.git
