apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-helmrelease.yaml
- db-helmrepo.yaml
- github-provider.yaml
- instavote-gitrepo.yaml
- redis-kustomization.yaml
- redis-staging-alert.yaml
- result-helmrelease.yaml
- result-imagepol.yaml
- result-imagerepo.yaml
- result-imageupdate.yaml
- slack-alert.yaml
- slack-provider.yaml
- vote-imagepol.yaml
- vote-imagerepo.yaml
- vote-imageupdate.yaml
- vote-kustomization.yaml
- vote-staging-alert.yaml
- worker-imagepol.yaml
- worker-imagerepo.yaml
- worker-imageupdate.yaml
- worker-kustomization.yaml
- worker-staging-alert.yaml
