---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: result-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm/charts/result
      sourceRef:
        kind: GitRepository
        name: instavote
  interval: 30s
  targetNamespace: instavote
