---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vote-staging
  namespace: flux-system
spec:
#  dependsOn:
#  - name: redis-staging
  healthChecks:
  - kind: Deployment
    name: vote
    namespace: instavote
  interval: 30s
  path: ./kustomize/vote/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  timeout: 2m0s
