---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: result-prod
  namespace: flux-system
spec:
  dependsOn:
  - name: db-prod
  healthChecks:
  - kind: Deployment
    name: result
    namespace: instavote
  interval: 1m0s
  path: ./kustomize/result/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  targetNamespace: instavote
  timeout: 2m0s
