---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: worker-prod
  namespace: flux-system
spec:
  dependsOn:
  - name: redis-prod
  - name: db-prod
  healthChecks:
  - kind: Deployment
    name: worker
    namespace: instavote
  interval: 1m0s
  path: ./kustomize/worker/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  targetNamespace: instavote
  timeout: 2m0s
