apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
namespace: instavote
replicas:
- name: vote
  count: 2
images:
- name: xvag/instavote-vote
  newName: xvag/vote
  newTag: main-b3db328c-1646733048 # {"$imagepolicy": "flux-system:vote:tag"}
