apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: result
  name: result
spec:
  ports:
  - name: 4000-4000
    nodePort: 30001
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: result
  type: NodePort
