apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml

namespace: instavote

replicas:
- name: worker
  count: 2

images:
- name: xvag/instavote-worker
#  newName: xvag/worker
  newTag: latest
